### ISSUE TITLE
Add Dyson sphere 

### ISSUE THREAD

**Issue by Aulluna** [gisellevonbingen/Minecraft-BossTools-Addon#14]
### The details

Apprently scaut isnt adding either dyson sphere , or space hooks . Maybe you could add them ? i can help you with structures of any of these suggested additions in case you need help .

**Comment by gisellevonbingen** [comment]
Originally, Addon mod was designed as a mod
to fill the lack of compatibility/convenience of Space-BossTools
(like tinker's complement)

That's why i don't add main stream like add planet
So I'm not going to add that structure to the Addon mod
That is great idea, but so sorry

Instead, if scaut provides a planet add API or if you have an idea for a planet,
I will create a new mod, maybe it can add that structure
